apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-db-abo
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: db-abo
spec:
  schedule: "7/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: db-abo
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: certs
              secret:
                secretName: vdv-pkpass-certs
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: django
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: Always
              command: ["sh", "-c", "python3 manage.py update-db-abo"]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
                - mountPath: "/certs"
                  name: certs
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-db-bc
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: db-bc
spec:
  schedule: "7 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: db-bc
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: certs
              secret:
                secretName: vdv-pkpass-certs
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: django
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: Always
              command: ["sh", "-c", "python3 manage.py update-db-bc"]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
                - mountPath: "/certs"
                  name: certs
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-saarvv
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: db-saarvv
spec:
  schedule: "7/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: db-saarvv
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: certs
              secret:
                secretName: vdv-pkpass-certs
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: django
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: Always
              command: ["sh", "-c", "python3 manage.py update-saarvv"]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
                - mountPath: "/certs"
                  name: certs
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-uic-certs
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: uic-certs
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: uic-certs
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: uic-certs
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py download-uic-certs"]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-uic-data
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: uic-data
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: uic-data
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: uic-data
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: IfNotPresent
              command: [ "sh", "-c", "python3 manage.py download-uic-data" ]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-vdv-orgs
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: vdv-orgs
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: vdv-orgs
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: vdv-orgs
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: IfNotPresent
              command: [ "sh", "-c", "python3 manage.py download-vdv-orgs" ]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vdv-pkpass-rsp-data
  namespace: q-personal
  labels:
    app: vdv-pkpass
    part: rsp-data
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
          labels:
            app: vdv-pkpass
            class: cron
            part: rsp-data
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: google-creds
              secret:
                secretName: vdv-pkpass-google-creds
          containers:
            - name: rsp-data
              image: theenbyperor/vdv-pkpass-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py download-rsp-data"]
              volumeMounts:
                - mountPath: "/google-creds"
                  name: google-creds
              envFrom:
                - configMapRef:
                    name: vdv-pkpass
                - secretRef:
                    name: vdv-pkpass-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: vdv-pkpass-email
                  prefix: "EMAIL_"
                - secretRef:
                    name: vdv-pkpass-django-secret
                - secretRef:
                    name: vdv-pkpass-s3
                - secretRef:
                    name: vdv-pkpass-nr
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vdv-pkpass-db-abo
  namespace: q-personal
spec:
  podSelector:
    matchLabels:
      app: vdv-pkpass
      class: cron
  policyTypes:
    - Ingress