# Generated by Django 5.0.9 on 2024-10-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_saarvv_acccount_ticket_saarvv_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('klimaticket', 'Klimaticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Fahrkarte'), ('reservierung', 'Reservierung'), ('interrail', 'Interrail'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
        migrations.CreateModel(
            name='RSP6TicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_id', models.CharField(max_length=2, verbose_name='Issuer ID')),
                ('reference', models.CharField(max_length=20, verbose_name='Ticket reference')),
                ('barcode_data', models.BinaryField()),
                ('decoded_data', models.JSONField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsp6_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'RSP6 ticket',
                'unique_together': {('reference', 'issuer_id')},
            },
        ),
    ]
