# Generated by Django 5.0.9 on 2024-11-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_rsp6ticketinstance_ticket_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsp6ticketinstance",
            name="ticket_type",
            field=models.CharField(
                default="06", max_length=2, verbose_name="Ticket type"
            ),
        ),
    ]
