# Generated by Django 5.0.9 on 2024-11-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_rsp6ticketinstance_ticket_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rsp6ticketinstance",
            unique_together={("ticket_type", "reference", "issuer_id")},
        ),
    ]
