# Generated by Django 5.0.9 on 2024-11-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_ticket_ticket_type_rspticketinstance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="photos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rspticketinstance",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsp_instances",
                to="main.ticket",
            ),
        ),
    ]
