# Generated by Django 5.0.9 on 2024-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_ticket_photos_alter_rspticketinstance_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="photos",
            field=models.JSONField(default={}),
        ),
    ]
