# Generated by Django 5.0.9 on 2024-11-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_elbticketinstance'),
        ('main', '0029_sncfticketinstance'),
    ]

    operations = [
    ]
