# Generated by Django 5.0.9 on 2024-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_merge_0022_elbticketinstance_0029_sncfticketinstance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appleregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appleregistration',
            name='ticket_part',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket part'),
        ),
        migrations.AlterUniqueTogether(
            name='appleregistration',
            unique_together={('ticket', 'device', 'ticket_part')},
        ),
    ]
