# Generated by Django 5.0.9 on 2024-11-25 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_appleregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSBTicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_rics', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS')),
                ('pnr', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='PNR')),
                ('barcode_data', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssb_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'SSB ticket',
            },
        ),
    ]
