# Generated by Django 5.0.9 on 2024-11-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_ssbticketinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('klimaticket', 'Klimaticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Fahrkarte'), ('reservierung', 'Reservierung'), ('interrail', 'Interrail'), ('railcard', 'Railcard'), ('keycard', 'Keycard'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
    ]
