# Generated by Django 5.0.9 on 2024-11-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssbticketinstance',
            name='pnr',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='PNR'),
        ),
    ]
