# Generated by Django 5.0.9 on 2024-12-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_ssbticketinstance_pnr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZHVStop',
            fields=[
                ('dhid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='DHID')),
                ('dhid_raw_id', models.CharField(max_length=255, verbose_name='DHID raw ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('municipality', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('authority', models.CharField(db_index=True, max_length=255)),
                ('thid', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.zhvstop')),
            ],
            options={
                'indexes': [models.Index(fields=['dhid_raw_id', 'authority'], name='main_zhvsto_dhid_ra_2ff5cf_idx')],
            },
        ),
    ]
