# Generated by Django 5.0.9 on 2024-12-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_zhvstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhvstop',
            name='parent',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.zhvstop'),
        ),
    ]
