# Generated by Django 5.0.9 on 2024-12-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_zhvstop_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhvstop',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.zhvstop'),
        ),
    ]
