# Generated by Django 5.0.9 on 2025-01-09 10:38
import hashlib

from django.db import migrations, models

def set_hash(apps, schema_editor):
    for m in ("ELBTicketInstance", "SNCFTicketInstance", "SSBTicketInstance", "UICTicketInstance", "VDVTicketInstance"):
        model = apps.get_model("main", m)
        for i in model.objects.all():
            i.barcode_hash = hashlib.sha256(i.barcode_data).hexdigest()
            i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_zhvstop_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elbticketinstance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='uicticketinstance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vdvticketinstance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sncfticketinstance',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='ssbticketinstance',
            name='pnr',
        ),
        migrations.AddField(
            model_name='elbticketinstance',
            name='barcode_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sncfticketinstance',
            name='barcode_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssbticketinstance',
            name='barcode_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uicticketinstance',
            name='barcode_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vdvticketinstance',
            name='barcode_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='elbticketinstance',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='elbticketinstance',
            name='sequence_number',
        ),
        migrations.RemoveField(
            model_name='uicticketinstance',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='vdvticketinstance',
            name='ticket_number',
        ),
        migrations.RunPython(set_hash, lambda a, s: None),
        migrations.AlterField(
            model_name='elbticketinstance',
            name='barcode_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sncfticketinstance',
            name='barcode_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ssbticketinstance',
            name='barcode_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='uicticketinstance',
            name='barcode_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vdvticketinstance',
            name='barcode_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
