# Generated by Django 5.0.9 on 2025-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_elbticketinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssbticketinstance',
            name='ssb_data',
            field=models.BinaryField(null=True),
        ),
    ]
