# Generated by Django 5.0.9 on 2025-01-20 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_elbticketinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSB1TicketInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_rics', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Distributor RICS')),
                ('barcode_hash', models.CharField(max_length=64, unique=True)),
                ('barcode_data', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssb1_instances', to='main.ticket')),
            ],
            options={
                'verbose_name': 'SSBv1 ticket',
            },
        ),
    ]
